# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

def shared_pods
	pod 'Alamofire'
	pod 'Gloss'
	pod 'Kingfisher', '~> 3.0'
	pod 'SwiftyJSON'
	pod 'KeychainAccess'
end
  
target 'whale_ios_nabil' do
  use_frameworks!
  shared_pods
end

target 'whale_ios_nabilTests' do
  use_frameworks!
  
  shared_pods
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
